[tool.ruff]
line-length = 170
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "COM812", "D212"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
